# Generated by Django 5.2.14 on 2026-05-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0003_usuario_endereco_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarte',
            name='coletor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes_coletados', to='ecosmart.usuario'),
        ),
        migrations.AddField(
            model_name='descarte',
            name='data_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descarte',
            name='instituicao_coletora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes_coletados', to='ecosmart.instituicao'),
        ),
    ]
