# Generated by Django 5.2.14 on 2026-05-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosmart', '0004_descarte_coletor_descarte_data_coleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descarte',
            name='pedido_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes', to='ecosmart.pedidocoleta'),
        ),
    ]
